id: IF23D2F62
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:54:24+00:00'
last_modified: '2022-06-08T16:09:23.419755+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ890
  title: རབ་བྱུང་མ་རྣམས་ལ་བསླབ་ཁྲིམས་སུ་བཅས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E72F:
      image_group_id: I1CZ1016
      title: ''
      total_pages: 18
      order: 1
      base_file: E72F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
