id: P010600
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:15:56.861350
source_metadata:
  id: bdr:W1CZ890
  title: རབ་བྱུང་མ་རྣམས་ལ་བསླབ་ཁྲིམས་སུ་བཅས་པ
  author: ''
  volumes:
    1640ac8ee992499d928b417a6e262a46:
      image_group_id: I1CZ1016
      title: ''
      volume_number: 1
      total_pages: 18
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
